#!/usr/bin/env bash

getWmInfo() {
    local WAYLAND_DISPLAY="$WAYLAND_DISPLAY"
    if [ -n "$WAYLAND_DISPLAY" ]; then
        local xdgDesktop="$XDG_CURRENT_DESKTOP"
        echo -e " ${xdgDesktop:-Unknown}"
    else
        local display=$(echo $DISPLAY)
        if [ -n "$display" ]; then
            local root=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F' ' '{print $NF}')
            local netWmName=$(xprop -id $root _NET_WM_NAME | awk -F' ' '{print $NF}')

            if [ -n "$netWmName" ]; then
                echo -e " $netWmName"
            else
                echo -e " Unknown"
            fi
        else
            echo -e "\ Unknown"
        fi
    fi
}

spacing() {
 echo
}

bunnyfetch() {
    echo -e ' ' ' ' ' ' ' ' '|  |' "$(whoami)@$(hostname)"
    echo -e  '(\ /)' '  |  |' $(lsb_release -i | cut -f 2-)
    echo -e '( . .)' ' |  |' $(uname -r)
    echo -e 'c(")(")' '|  |' $(getWmInfo)
    echo -e ' ' ' ' ' ' ' '' | + |'' 1.0.0'
}

noasciifetch() {
    echo -e "+-----------+---+--------------------------------+"
    echo -e "| distro      |"   $(lsb_release -i | cut -f 2-)
    echo -e "| username    |"   $(whoami)@$(hostname)
    echo -e "| kernel      |"   $(uname -r)
    echo -e "| wm          |"   $(getWmInfo)
    echo -e "| fetch ver   |"   "1.0.0"
    echo -e "+-----------+---+--------------------------------+"
}

starttroll() {
 bunnyfetch
 spacing
 noasciifetch
 spacing
 home
}

start() {
 bunnyfetch
}

start
