#!/usr/bin/env bash

getWmInfo() {
    local WAYLAND_DISPLAY="$WAYLAND_DISPLAY"
    if [ -n "$WAYLAND_DISPLAY" ]; then
        local xdgDesktop="$XDG_CURRENT_DESKTOP"
        echo -e " ${xdgDesktop:-Unknown}"
    else
        local display=$(echo $DISPLAY)
        if [ -n "$display" ]; then
            local root=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F' ' '{print $NF}')
            local netWmName=$(xprop -id $root _NET_WM_NAME | awk -F' ' '{print $NF}')

            if [ -n "$netWmName" ]; then
                echo -e " $netWmName"
            else
                echo -e " Unknown"
            fi
        else
            echo -e "\ Unknown"
        fi
    fi
}

spacing() {
 echo
}

bunny() {
    echo -e  '(\ /)' '  |  |' $(lsb_release -i | cut -f 2-)
    echo -e '( . .)' ' |  |' $(uname -r)
    echo -e 'c(")(")' '|  |' $(getWmInfo)
}



longline() {
 echo ----------------
}

usrname() {
 echo ' ' ' ' ' ' ' ' '|  |'"$(whoami)@$(hostname)"
}

fetch() {
 usrname
 bunny
 echo -e ' ' ' ' ' ' ' '' | + |'' 1.0.0'
}


fetch
